### ISSUE TITLE
実線設定の図形が破線で表示される

### ISSUE THREAD

**Issue by maynbow** [thinreports-php/thinreports-php#4]
## 内容

図形の線の種類に破線を設定し、PDFを出力すると実線に設定されている図形も破線で表示されることがある。
### 設定

![default](https://cloud.githubusercontent.com/assets/13758296/9216401/ab7709fe-40f3-11e5-9ccc-4acb4a3338a2.png)
### 結果

![pdf](https://cloud.githubusercontent.com/assets/13758296/9216409/c1b00fe0-40f3-11e5-9152-772c49e51b09.png)
## 実行環境
- Windows 7 32bit
- Chrome 44
- PHP 5.5
- thinreports-editor 0.8.2
- thinreports-php 0.8.0-alpha2

**Comment by hidakatsuya** [comment]
@maynbow 

ご報告ありがとうございます。調査します。

**Comment by mikkame** [comment]
@maynbow
同じ症状が出まして、修正できましたのでご報告申し上げます。
現在の実装では、破線を使わない場合は、"none"を渡していますが
正しくは、"0"を渡すのが、TCPDFのドキュメントは正しいようでした。

"none"だった場合"0"に置き換える処理を組み込みんだ所、エディターと同様の表示ができました。
プルリクを投げましたので、マージして動作確認してみてください。

**Comment by hidakatsuya** [comment]
@maynbow @mikkame #13 と 5556302fb9b403e45dd1a85314c4d4dc7ba62f41 で修正しました。ご報告・ご協力ありがとうございました。
